package ru.job4j.generics;

/**
 * Represents some base entity.
 *
 * @author Alexey Aleshin
 * @version $id$
 * @since 26.08.17
 */
public abstract class Base {

    /**
     * Identifier.
     */
    private String id;

    /**
     * Identifier setter.
     *
     * @param id some id as a string
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Identifier getter.
     *
     * @return id as a string
     */
    public String getId() {
        return id;
    }

    /**
     * Generated by Idea.
     *
     * @param o some object
     * @return true if given object has the same id, otherwise returns false
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        Base base = (Base) o;

        return id.equals(base.id);
    }

    /**
     * Generated by Idea.
     *
     * @return hash as int
     */
    @Override
    public int hashCode() {
        return id.hashCode();
    }
}
